### ISSUE TITLE
Header field at 0x30 may be more then just a CR

### ISSUE THREAD

**Issue by eriksejr** [vasvir/tcrevenge#1]
Hello,
First thank you for your work on this. I am working with a device which uses what I believe is an updated version of the TC3162. Probably a TC3262 or RT/MT6856. The firmware & flash layout seems exactly the same, and the checksum calculation works out precisely against the factory firmware so this tool seems valid with the device as well.

Although I have not yet tried to flash a modified image one thing I did notice is the firmware header is slightly different at offset 0x30. Where you had only an 0x0a at that location I have a longer string terminated with an 0x0a:

```
[erik@eriks tcrevenge]$ hexdump -n 256 -C censored-filename.bin
00000000  32 52 44 48 00 00 01 00  00 ad b3 73 ad d5 db d1  |2RDH.......s....|
00000010  37 2e 30 2e 31 2e 30 0a  00 00 00 00 00 00 00 00  |7.0.1.0.........|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  35 56 4d 44 44 52 41 35  0a 00 00 00 00 00 00 00  |5VMDDRA5........|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 10 f2 73 00 9c c0 00  00 00 00 00 36 33 30 30  |...s........6300|
00000060  4e 5a 4c 0a 00 00 00 00  00 00 00 00 00 00 00 00  |NZL.............|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000100
[erik@eriks tcrevenge]$ hexdump -C header
00000000  32 52 44 48 00 00 01 00  00 ad b3 73 ad d5 db d1  |2RDH.......s....|
00000010  37 2e 30 2e 31 2e 30 0a  00 00 00 00 00 00 00 00  |7.0.1.0.........|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  0a 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 10 f2 73 00 9c c0 00  00 00 00 00 36 33 30 30  |...s........6300|
00000060  4e 5a 4c 0a 00 00 00 00  00 00 00 00 00 00 00 00  |NZL.............|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000100
```
I am guessing this may be simply some sort of firmware description field that was unused (and hence simply terminated) in your example. I will try to flash with the new header and see if it matters but I thought you might be interested.

**Comment by vasvir** [comment]
Sure let me know what happened so I can close the issue.

**Comment by eriksejr** [comment]
I have two different devices from this manufacturer. Both require a different value in this field. If left as just a newline the device will not take the image (indicates the image is "illegal"). I have submitted a pull request to add a CLI switch to modify this value. I have called it a "board ID" or simply "board" but you can name it whatever you like since the contents of the field provide absolutely no help in guessing what it is for (like the above the other is seemingly just random numbers and letters).
