### ISSUE TITLE
Ask About Posibility to Build Custom Kernel and How to get Kernel from dumped flash

### ISSUE THREAD

**Issue by ndunks** [vasvir/tcrevenge#4]
Hello, thanks for the great work it help me alot. 

I also still inspecting ZXHN-H108N device, this my [repo](https://github.com/ndunks/modem-indihome-huawei-ZXHN-H108N)

I'm not expert on this field, but somebody there may give me some though.

I know that ZXHN-H108N with Broadcom chipset is works with OpenWRT, but in my case I have Ralink chipset. It is possible to build custom kernel for it? or any suggestion?

in my repo you can see there is a `firmware.bin` file dumped from the nor flash sotrage directly using CH341, but i can't figure where is the Kernel and rootfs. can you give some clues? please check it here: https://github.com/ndunks/modem-indihome-huawei-ZXHN-H108N/tree/main/firmware

**Comment by vasvir** [comment]
Hi,

I played a bit with binwalk but I also cannot figure out the layout or where the rootfs is. It is different from my device.

I am sorry I can't help.

**Comment by ndunks** [comment]
yes I got the same experience. thanks for your efforts.
I think its compressed with non standard archive format (or its directly an MIPS instruction codes with self extract/decompile), need to know the toolchain to reverse it. I did some research and add some links that may related to the SDK/toolchain (https://github.com/HyGw/test)
